<a href="https://colab.research.google.com/github/rupeshthapa123/NotebookProject/blob/main/RupeshThapa_Lab10_ArtificialNeuralNetworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab10. Artificial Neural Networks

In this lab you will implement a basic Artificial Neural Network using a multilayer perceptron architecture. The Fashion MNIST dataset is used to train a model that classifies images of clothes.

# Dataset

Import the Fashion MNIST dataset using Keras. Show the shape and data type of the data.

In [ ]:
import keras

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test)= fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


Create a validation dataset from the original dataset and scale the train/validation dataset to a range of 0 to 1

In [ ]:
X_train_full.shape

(60000, 28, 28)

In [ ]:
X_train_full.dtype

dtype('uint8')

In [ ]:
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [ ]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]
class_names[y_train[0]]

'Coat'

# Sequential ANN Model

Use the Sequential function to create a sequential model with two hidden layers using:
- One 28x28 input layer flattened to a vector
- Two dense layers of 300 and 100 neurons **using** relu activation
- One output layer with 10 outputs using **softmax** activation function

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

Show the summary and layers for your model

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266610 (1.02 MB)
Trainable params: 266610 (1.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.layers

In [ ]:
hidden1 = model.layers[1]
hidden1.name

'dense'

In [ ]:
model.get_layer('dense') is hidden1

True

Show the weights and biases of your model

In [ ]:
weights, biases = hidden1.get_weights()

In [ ]:
weights

array([[-0.01989499,  0.01927517,  0.06700718, ...,  0.07048884,
         0.05265251, -0.04459247],
       [ 0.01746962,  0.00277495,  0.03367725, ...,  0.03294134,
         0.0618834 ,  0.03014299],
       [ 0.06198838, -0.02949314,  0.0204529 , ..., -0.00873221,
        -0.05074516, -0.03144017],
       ...,
       [-0.00251168,  0.02404235,  0.03754082, ..., -0.05005417,
        -0.04876741,  0.03019466],
       [-0.03508861, -0.06054517,  0.01681057, ...,  0.06193858,
         0.06167658, -0.06558368],
       [ 0.01457798, -0.06499345,  0.0202755 , ..., -0.06232979,
         0.03276701,  0.00978328]], dtype=float32)

In [ ]:
weights.shape

(784, 300)

In [ ]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
biases.shape

(300,)

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

Train the model using your dataset

In [ ]:
history = model.fit(X_train, y_train, epochs=30,
                    validation_data=(X_valid, y_valid))

Epoch 1/30
1719/1719 [==============================] - 18s 9ms/step - loss: 0.7269 - accuracy: 0.7612 - val_loss: 0.5021 - val_accuracy: 0.8308
Epoch 2/30
1719/1719 [==============================] - 7s 4ms/step - loss: 0.4890 - accuracy: 0.8292 - val_loss: 0.4761 - val_accuracy: 0.8336
Epoch 3/30
1719/1719 [==============================] - 7s 4ms/step - loss: 0.4437 - accuracy: 0.8442 - val_loss: 0.4588 - val_accuracy: 0.8350
Epoch 4/30
1719/1719 [==============================] - 6s 4ms/step - loss: 0.4170 - accuracy: 0.8530 - val_loss: 0.3984 - val_accuracy: 0.8604
Epoch 5/30
1719/1719 [==============================] - 7s 4ms/step - loss: 0.3948 - accuracy: 0.8619 - val_loss: 0.3869 - val_accuracy: 0.8676
Epoch 6/30
1719/1719 [==============================] - 6s 4ms/step - loss: 0.3791 - accuracy: 0.8666 - val_loss: 0.3831 - val_accuracy: 0.8656
Epoch 7/30
1719/1719 [==============================] - 7s 4ms/step - loss: 0.3642 - accuracy: 0.8716 - val_loss: 0.3618 - val_accuracy

Evaluate the performance of your model and show accuracy and loss.

In [ ]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 62.3087 - accuracy: 0.8545


[62.30873107910156, 0.8544999957084656]

Use the last five samples in the test dataset and predict their classes using **predict** and **predict_proba** functions

In [ ]:
X_new = X_test[:5]
y_proba = model.predict(X_new)
y_proba.round(2)

1/1 [==============================] - 0s 89ms/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

The function predict_classes was removed from tensor flow. That is why I am using new method for the below code.

In [ ]:
import numpy as np
y_pred = np.argmax(model.predict(X_new), axis=1)
y_pred

1/1 [==============================] - 0s 23ms/step


array([9, 2, 1, 1, 6])

In [ ]:
np.array(class_names)[y_pred]

array(['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt'],
      dtype='<U11')